### ISSUE TITLE
Adding URL to 'description' 

### ISSUE THREAD

**Issue by nickcolley** [alphagov/dcs-pilot-docs#141]
If you get a sec could you add https://dcs-pilot-docs.cloudapps.digital/ to the 'website' section on the repo?

For example
<img width="629" alt="Screenshot 2020-03-20 at 11 44 12" src="https://user-images.githubusercontent.com/2445413/77160838-24076f00-6aa0-11ea-9aa3-0c18d6484b66.png">

I use this to automatically populate a spreadsheet:

https://docs.google.com/spreadsheets/d/1Srd1hdpZ0M0DnAPVObvGWomf5QQF7LodSaAhuatidbc/edit#gid=108113909

**Comment by mrwilson** [comment]
Hey Nick, I've done that manually for now and I'll add it to our Terraform repository configuration so it's version controlled later today. 👍

**Comment by nickcolley** [comment]
@mrwilson epic thanks!
