### ISSUE TITLE
Add a reference to the code of conduct

### ISSUE THREAD

**Issue by pauldougan** [alphagov/dcs-pilot-docs#37]

**Comment by bravegrape** [comment]
Fixed by PR https://github.com/alphagov/dcs-pilot-docs/pull/71

**Comment by bravegrape** [comment]
Fixed by PR https://github.com/alphagov/dcs-pilot-docs/pull/71

**Comment by bravegrape** [comment]
Fixed by PR https://github.com/alphagov/dcs-pilot-docs/pull/71
