### ISSUE TITLE
Document our workflow so that the team can understand what is expected

### ISSUE THREAD

**Issue by pauldougan** [alphagov/dcs-pilot-docs#38]
Provide some guidance on how to contribute to the DCS Pilot  documentation repository

- raising issues to ask for clarification, additional documentation etc.
- how we will manage pull requests
- code ownership and who is able to merge to master
- standardised templates for pull requests

**Comment by mrwilson** [comment]
I'm going to mark this as closed as I think this is "good enough".

We've got a pull request template, the README details how to contribute/preview alongside the code of conduct.
