### ISSUE TITLE
Add guidance on testing so that a connecting organisation can test their implementation

### ISSUE THREAD

**Issue by pauldougan** [alphagov/dcs-pilot-docs#39]
We require connecting organisations to create a client to interface to the DCS API to manage the JOSE signing and encryption.

To validate their implementation they will need to be able to make test requests against an API endpoint. 

The guidance must explain:

- the location of the endpoint
- any limitations or restrictions
- availability 
- how to test against the endpoint. e.g. how to test a successful request and how to test an unsucessful request

**Comment by mrwilson** [comment]
We have now done this with published sample data, CA bundles/certs for the integration environment, and the integration environment url.

These docs have gone through two rounds of user testing to improve them, too :)
