### ISSUE TITLE
Add concrete examples of JOSE messages to clarify the signing and encryption process

### ISSUE THREAD

**Issue by pauldougan** [alphagov/dcs-pilot-docs#55]
Extend the documentation with more comprehensive examples of the payload to full explain how a connecting organisation signs and encrypts a checking request.

To avoid any ambiguity we need to be explicit.

Need examples for:
- check DCS Status
- check passport

**Comment by benjamin-mortimer** [comment]
Done: https://dcs-pilot-docs.cloudapps.digital/sign-and-encrypt-a-DCS-payload/#sign-and-encrypt-a-dcs-payload
