### ISSUE TITLE
Ensure the DCS API Documentation is in line with the current API Guidance

### ISSUE THREAD

**Issue by pauldougan** [alphagov/dcs-pilot-docs#74]
The [API Design Guidance](https://www.gov.uk/government/collections/api-design-guidance) defines best practice for APIs.

We should review the DCS API documentation in the light of this guidance to make sure we are using best practice. 

The following are particularly relevant: 

- [ API technical and data standards (v2 - 2019)](https://www.gov.uk/guidance/gds-api-technical-and-data-standards)
- [How to document APIS ](https://www.gov.uk/guidance/how-to-document-apis) 
- [Writing API reference documentation ](https://www.gov.uk/guidance/writing-api-reference-documentation)

**Comment by mrwilson** [comment]
We're talking to the Data Standards and Assurance group about getting the DCS through an API critique and self-assessing against the guidelines.

I'll close this for now, as these wheels are in motion and it's not _specifically_ a documentation issue.
