### ISSUE TITLE
mention that you can also raise a pull request against the repo as well as raising an issue on the support page

### ISSUE THREAD

**Issue by pauldougan** [alphagov/dcs-pilot-docs#75]
dcs-pilot-docs.cloudapps.digital/support/

suggested enhancement 

```
If you’d like to offer feedback or report a problem with this documentation website, open an issue on GitHub or raise a pull request.
```

to make it clear that we are happy to accept changes via PR

**Comment by mrwilson** [comment]
Cheers Paul, this has been included now!

https://dcs-pilot-docs.cloudapps.digital/support/#support
