### ISSUE TITLE
Re: 'Integrating with the Document Checking Service'

### ISSUE THREAD

**Issue by pauldougan** [alphagov/dcs-pilot-docs#83]
Problem with 'Integrating with the Document Checking Service' (dcs-pilot-docs.cloudapps.digital/integrating-with-the-dcs/)

This page says:
> Details about how to raise a certificate signing request with our Certificate Authority will follow after the expression of interest stage of the DCS pilot.

The EOI stage is now closed and we need to add more documentation to describe how a pilot organisation requests the necessary certificates so that they can actually use our API

**Comment by benjamin-mortimer** [comment]
Done! https://dcs-pilot-docs.cloudapps.digital/generate-keys-and-request-certificates/#generate-keys-and-request-certificates
