### ISSUE TITLE
Consider adding some guidance on useful libraries for handling the creation of valid JOSE objects

### ISSUE THREAD

**Issue by pauldougan** [alphagov/dcs-pilot-docs#84]
Problem with 'Integrating with the Document Checking Service' (dcs-pilot-docs.cloudapps.digital/integrating-with-the-dcs/)

The documentation leaves the choice or programming language to the connecting organisation

> It’s up to you to decide which programming language your client is using. 

We should consider providing  guidance on useful language specific libraries for handling JOSE requests. 

e.g. `pycrypto` for python 

https://pypi.org/project/pycrypto/

**Comment by benjamin-mortimer** [comment]
This is now done: https://dcs-pilot-docs.cloudapps.digital/sign-and-encrypt-a-DCS-payload/#choose-a-library-to-use-for-jws-and-jwe
